spring:
  zipkin:
    base-url: http://localhost:9411/
  redis:
    connect-timeout: 3s
    host: localhost
    port: 6379
    timeout: 50ms
    database: 0

springdoc:
  packagesToScan: com.app
  

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
